# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arrowstream.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'arrowstream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61rrowstream.proto\x12\x06stream\"\x0f\n\rStreamRequest\"\r\n\x0bStopRequest\"%\n\x0eStreamResponse\x12\x13\n\x0b\x61rrow_table\x18\x01 \x01(\x0c\"\x1f\n\x0cStopResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x88\x01\n\rStreamService\x12>\n\x0bStartStream\x12\x15.stream.StreamRequest\x1a\x16.stream.StreamResponse0\x01\x12\x37\n\nStopStream\x12\x13.stream.StopRequest\x1a\x14.stream.StopResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arrowstream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=29
  _globals['_STREAMREQUEST']._serialized_end=44
  _globals['_STOPREQUEST']._serialized_start=46
  _globals['_STOPREQUEST']._serialized_end=59
  _globals['_STREAMRESPONSE']._serialized_start=61
  _globals['_STREAMRESPONSE']._serialized_end=98
  _globals['_STOPRESPONSE']._serialized_start=100
  _globals['_STOPRESPONSE']._serialized_end=131
  _globals['_STREAMSERVICE']._serialized_start=134
  _globals['_STREAMSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
